repos:
  - repo: local
    hooks:
      - id: checkFormatting-all
        name: Check formatting for the entire codebase
        language: system
        entry: task checkFormatting-all
        pass_filenames: false

      - id: lint-all
        name: Lint the entire codebase
        language: system
        entry: task lint-all
        pass_filenames: false

      - id: analyze-all
        name: Analyze the entire codebase
        language: system
        entry: task analyze-all
        pass_filenames: false
