version: '3'

includes:
  infra:
    taskfile: infra/Taskfile.yml
    dir: infra

  counter-web:
    taskfile: apps/counter-web/frontend/Taskfile.yml
    dir: apps/counter-web/frontend

tasks:
  github-ci:lint:
    desc: Lint GitHub workflows
    sources:
      - '.github/workflows/*.yml'
    cmds:
      - github-ci lint

  github-ci:fixLint:
    desc: Fix lint issues in GitHub workflows
    sources:
      - '.github/workflows/*.yml'
    cmds:
      - github-ci lint --fix

  github-ci:upgrade:
    desc: Upgrade GitHub workflow actions to the latest versions
    cmds:
      - github-ci upgrade

  checkFormatting-all:
    desc: Check formatting for the entire codebase
    deps: [ infra:checkFormatting, github-ci:lint, counter-web:checkFormatting ]

  fixFormatting-all:
    desc: Fix formatting for the entire codebase
    deps: [ infra:fixFormatting, github-ci:fixLint, counter-web:fixFormatting ]

  lint-all:
    desc: Lint the entire codebase
    deps: [ infra:lint, github-ci:lint, counter-web:lint ]

  analyze-all:
    desc: Analyze the entire codebase
    deps: [ infra:validate, counter-web:typecheck ]
