version: '3'

includes:
  infra:
    taskfile: infra/Taskfile.yml
    dir: infra

  web:app:
    taskfile: apps/web/spa/Taskfile.yml
    dir: apps/web/spa

  web:infra:
    taskfile: apps/web/infra/Taskfile.yml
    dir: apps/web/infra

  core-service:impl:
    taskfile: services/core-service/impl/Taskfile.yml
    dir: services/core-service/impl

  core-service:infra:
    taskfile: services/core-service/infra/Taskfile.yml
    dir: services/core-service/infra

tasks:
  github-ci:lint:
    desc: Lint GitHub workflows
    sources:
      - '.github/workflows/*.yml'
    cmds:
      - github-ci lint

  github-ci:fixLint:
    desc: Fix lint issues in GitHub workflows
    sources:
      - '.github/workflows/*.yml'
    cmds:
      - github-ci lint --fix

  github-ci:upgrade:
    desc: Upgrade GitHub workflow actions to the latest versions
    cmds:
      - github-ci upgrade

  checkFormatting-all:
    desc: Check formatting for the entire codebase
    deps:
      - github-ci:lint
      - infra:checkFormatting
      - web:app:checkFormatting
      - web:infra:checkFormatting
      - core-service:impl:checkFormatting
      - core-service:infra:checkFormatting

  fixFormatting-all:
    desc: Fix formatting for the entire codebase
    deps:
      - github-ci:fixLint
      - infra:fixFormatting
      - web:app:fixFormatting
      - web:infra:fixFormatting
      - core-service:impl:fixFormatting
      - core-service:infra:fixFormatting

  lint-all:
    desc: Lint the entire codebase
    deps:
      - github-ci:lint
      - infra:lint
      - web:app:lint
      - web:infra:lint
      - core-service:impl:lint
      - core-service:infra:lint

  analyze-all:
    desc: Analyze the entire codebase
    deps:
      - infra:validate
      - web:app:analyze
      - web:infra:validate
      - core-service:infra:validate

  run:
    desc: Run the frontend and core service locally
    deps:
      - web:app:run
      - core-service:impl:run
