# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

.terraformSources: &terraformSources
  - '**/*.tf'

tasks:
  checkFormatting:
    desc: Check Terraform formatting
    sources: *terraformSources
    cmds:
      - terraform fmt -check -recursive

  fixFormatting:
    desc: Fix Terraform formatting
    sources: *terraformSources
    cmds:
      - terraform fmt -recursive

  lint:
    desc: Lint the Terraform sources
    sources: *terraformSources
    cmds:
      - tflint --recursive

  validate:
    desc: Validate the Terraform configuration
    sources: *terraformSources
    cmds:
      - terraform validate
