# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  install:
    desc: Install dependencies
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json
    cmds:
      # Using `npm ci` ensures a clean install based on the lockfile
      - npm ci

  proto:
    desc: Generate code from protobuf definitions
    sources:
      - ../../../../proto/**/*.proto
    generates:
      - src/gen/**/*.ts
    cmds:
      - buf generate

  checkFormatting:
    desc: Check package formatting
    deps: [install]
    cmds:
      - npx prettier --check .

  fixFormatting:
    desc: Fix package formatting
    deps: [install]
    cmds:
      - npx prettier --write .

  lint:
    desc: Lint the package
    deps: [install, proto]
    cmds:
      - npx eslint .

  typecheck:
    desc: Type check the package
    deps: [install, proto]
    cmds:
      - npx tsc --noEmit

  clean:
    desc: Remove generated and build artifacts
    cmds:
      - rm -rf dist src/gen

  build:
    desc: Build the package
    deps: [install, typecheck, proto]
    cmds:
      - npx vite build

  dev:
    desc: Start dev server
    deps: [install, proto]
    env:
      VITE_COUNTER_SERVICE_URL: http://localhost:8081
    cmds:
      - npx vite
    interactive: true

  preview:
    desc: Start preview server
    deps: [build]
    cmds:
      - npx vite preview
    interactive: true
