version: '3'

.goSources: &go-sources
  - '**/*.go'
  - go.mod

tasks:
  checkFormatting:
    desc: Check Go formatting
    sources: *go-sources
    cmds:
      - test -z "$(gofmt -l .)"

  fixFormatting:
    desc: Fix Go formatting
    sources: *go-sources
    cmds:
      - gofmt -w .

  lint:
    desc: Lint the Go sources
    sources: *go-sources
    cmds:
      - golangci-lint run

  build:
    desc: Build the binary
    sources: *go-sources
    generates:
      - out/backend
    cmds:
      - go build -o out/backend .

  run:
    desc: Run the HTTP server
    env:
      PORT: '8080'
      FRONTEND_DIST_DIR: ../frontend/dist
    cmds:
      - go run .
    interactive: true
