name: Check PR

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-workflows:
    name: workflows
    uses: ./.github/workflows/check-workflows.yml

  check-infra:
    name: infra
    uses: ./.github/workflows/check-infra.yml

  check-counter-web-infra:
    name: counter-web (infra)
    uses: ./.github/workflows/check-counter-web-infra.yml
    secrets: inherit

    permissions:
      contents: read
      id-token: write
      pull-requests: write

  check-counter-web-app:
    name: counter-web (app)
    uses: ./.github/workflows/check-counter-web-app.yml
