name: pre-commit

on:
  push:
    branches: [main]
  pull_request:

env:
  NODE_VERSION: 24
  TERRAFORM_VERSION: 1.14

  TF_INPUT: false
  TF_CLI_ARGS: -no-color
  NO_COLOR: 1

permissions: read-all

# All required jobs should be marked as such in Terraform `0-bootstrap` config
jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: apps/counter-web/frontend/package-lock.json

      - uses: go-task/setup-task@v2

      - name: Install counter-web dependencies
        run: task install
        working-directory: apps/counter-web

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.x"

      - name: Install github-ci
        run: |
          go install github.com/reugn/github-ci/cmd/github-ci@latest
          echo "$HOME/go/bin" >> "$GITHUB_PATH"

      - uses: hashicorp/setup-terraform@v4.0.0
        with:
          terraform_version: ~> ${{ env.TERRAFORM_VERSION }}

      - uses: terraform-linters/setup-tflint@v6.2.2

      - uses: pre-commit/action@v3.0.1
