name: counter-web (app)

on:
  push:
    branches: ["trunk/*"]
    paths: &trigger-paths
      - "apps/counter-web/app/**"

  pull_request:
    paths: *trigger-paths

permissions:
  contents: read

env:
  NODE_VERSION: 24
  GO_VERSION: 1.26
  NO_COLOR: 1

  FRONTEND_PATH: apps/counter-web/app/frontend
  BACKEND_PATH: apps/counter-web/app/backend

jobs:
  build-frontend:
    name: Build frontend (counter-web)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.FRONTEND_PATH }}/package-lock.json

      - uses: go-task/setup-task@v2

      - name: Check formatting and lint
        run: task checkFormatting lint
        working-directory: ${{ env.FRONTEND_PATH }}

      - name: Build frontend
        run: task build
        working-directory: ${{ env.FRONTEND_PATH }}

  build-backend:
    name: Build backend (counter-web)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: ${{ env.BACKEND_PATH }}/go.sum

      - uses: go-task/setup-task@v2

      - name: Check formatting
        run: task checkFormatting
        working-directory: ${{ env.BACKEND_PATH }}

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ${{ env.BACKEND_PATH }}

      - name: Build backend
        run: task build
        working-directory: ${{ env.BACKEND_PATH }}
